version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  target-branch: "develop"
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - ulcuber
  assignees:
    - ulcuber
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  target-branch: "develop"
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - ulcuber
  assignees:
    - ulcuber
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
